Repository mamedev/mame, pull requests merged in 2024-05, with the labels that each got.

#12317 mz700_cass.xml: Metadata updates
  hash/mz700_cass.xml
Labels: SW list

#12180 mr/nl_drlibling.cpp: Fixed the PARATA netlist and optimized performance
  src/lib/netlist/generated/static_solvers.cpp
  src/lib/netlist/nl_create_mame_solvers.sh
  src/mame/mr/dribling.cpp
  src/mame/mr/nl_dribling.cpp
Labels: netlist

#12321 Add a skeleton driver for Cubieboard4 (CC A-80) single board computer
  hash/cubieboard4.xml
  src/mame/mame.lst
  src/mame/skeleton/cubieboard4.cpp
Labels: driver, SW list

#10461 a7800.xml: Updated some publication years.
  hash/a7800.xml
Labels: SW list

#12335 misc/micro3d.cpp: Cleanups:
  src/mame/misc/micro3d.cpp
  src/mame/misc/micro3d.h
  src/mame/misc/micro3d_a.cpp
  src/mame/misc/micro3d_a.h
  src/mame/misc/micro3d_m.cpp
  src/mame/misc/micro3d_v.cpp
Labels: Modernization

#12324 promat/3x3puzzl.cpp: Cleanups
  src/mame/promat/3x3puzzl.cpp
Labels: Modernization

#12323 promat/1945kiii.cpp: Use generic gfx decode layout, Cleanups:
  src/mame/promat/1945kiii.cpp
Labels: Modernization

#12318 midway/midzeus.cpp: Split driver state class per IO config, Cleanups:
  src/mame/midway/midzeus.cpp
  src/mame/midway/midzeus.h
  src/mame/midway/midzeus_v.cpp
Labels: Modernization
